- name: Database Bootstrap (MySQL Server Setup)
  hosts: db
  become: yes

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    # Variables externas desde GitHub Actions
    DB_NAME: "{{ db_name | default('movie_db') }}"
    DB_USER: "{{ db_user | default('usuario') }}"
    DB_PASS: "{{ db_pass | default('usuario') }}"

  tasks:
    # -------------------------------------------------------------------------
    # Prevent dpkg lock
    # -------------------------------------------------------------------------
    - name: Wait for dpkg lock (10 min timeout)
      shell: |
        echo "Waiting for dpkg/apt locks..."
        start=$(date +%s)

        while sudo lsof /var/lib/dpkg/lock >/dev/null 2>&1 \
           || sudo lsof /var/lib/dpkg/lock-frontend >/dev/null 2>&1 \
           || sudo lsof /var/lib/apt/lists/lock >/dev/null 2>&1 \
           || sudo lsof /var/cache/apt/archives/lock >/dev/null 2>&1; do

          now=$(date +%s)
          elapsed=$(( now - start ))

          echo "Still locked... elapsed ${elapsed}s"
          sleep 5

          if [ $elapsed -gt 600 ]; then
            echo "ERROR: dpkg lock timeout (10 minutes) — aborting."
            exit 1
          fi
        done

        echo "dpkg/apt lock released."
      changed_when: false

    # -------------------------------------------------------------------------
    # System update
    # -------------------------------------------------------------------------
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: yes

    # -------------------------------------------------------------------------
    # Install MySQL Server
    # -------------------------------------------------------------------------
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL running and enabled
      systemd:
        name: mysql
        state: started
        enabled: yes

    # -------------------------------------------------------------------------
    # Allow remote access
    # -------------------------------------------------------------------------
    - name: Allow external connections
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify: Restart mysql

    # -------------------------------------------------------------------------
    # Python dependencies for Ansible mysql modules
    # -------------------------------------------------------------------------
    - name: Install Python MySQL deps (pip)
      apt:
        name:
          - python3-pip
        state: present
        update_cache: yes

    - name: Install PyMySQL
      pip:
        name: PyMySQL
        executable: pip3

    # -------------------------------------------------------------------------
    # Fix root authentication (Ubuntu uses auth_socket by default)
    # -------------------------------------------------------------------------

    - name: Set MySQL root password & change root plugin
      shell: |
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpass';"
        sudo mysql -e "FLUSH PRIVILEGES;"
      args:
        executable: /bin/bash

    - name: Ensure root password works
      mysql_info:
        login_user: root
        login_password: rootpass
      register: root_auth
      failed_when: root_auth.failed

    # -------------------------------------------------------------------------
    # Create application user
    # -------------------------------------------------------------------------

    - name: Create application DB user
      mysql_user:
        name: "{{ DB_USER }}"
        password: "{{ DB_PASS }}"
        host: "%"
        priv: "*.*:ALL"
        state: present
        login_user: root
        login_password: rootpass

    # -------------------------------------------------------------------------
    # Create main database
    # -------------------------------------------------------------------------
    - name: Create database
      mysql_db:
        name: "{{ DB_NAME }}"
        state: present
        login_user: root
        login_password: rootpass

    # -------------------------------------------------------------------------
    # Clone repo to access SQL file
    # -------------------------------------------------------------------------
    - name: Clone API repo (SQL schema)
      git:
        repo: "https://github.com/joanroamora/movie-analyst-api.git"
        dest: /home/ubuntu/movie-analyst-api
        version: main

    # -------------------------------------------------------------------------
    # Import SQL schema + inserts
    # -------------------------------------------------------------------------

    - name: Load SQL schema
      mysql_db:
        state: import
        name: "{{ DB_NAME }}"
        target: "/home/ubuntu/movie-analyst-api/data_model/table_creation_and_inserts.sql"
        login_user: root
        login_password: rootpass

  handlers:
    - name: Restart mysql
      systemd:
        name: mysql
        state: restarted
