- name: Backend Bootstrap and Deployment
  hosts: backend
  become: yes

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    APP_IMAGE: "{{ app_image }}"
    DB_HOST: "{{ db_host }}"
    DB_USER: "{{ db_user | default('usuario') }}"
    DB_PASS: "{{ db_pass | default('usuario') }}"
    DB_NAME: "{{ db_name | default('movie_db') }}"
    JAEGER_IP: "{{ jaeger_ip }}"
    # Usamos la variable del inventario (ej: prod) o 'development' por defecto
    RUNTIME_ENV: "{{ app_env | default('development') }}" 

  tasks:

    # --- Prevent dpkg locks ----------------------------------------------------
    - name: Wait for dpkg lock
      shell: |
        while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for dpkg lock..."
          sleep 5
        done
      changed_when: false

    # --- Basic Packages --------------------------------------------------------
    - name: Install base tools
      apt:
        name:
          - curl
          - jq
          - ca-certificates
        state: present
        update_cache: yes

    # --- SSM Agent -------------------------------------------------------------
    - name: Check if SSM Agent installed
      command: which amazon-ssm-agent
      register: ssm_check
      ignore_errors: yes

    - name: Install SSM Agent via snap if missing
      snap:
        name: amazon-ssm-agent
        classic: yes
        state: present
      when: ssm_check.rc != 0
      ignore_errors: yes

    - name: Install SSM Agent via apt as fallback
      apt:
        name: amazon-ssm-agent
        state: present
      when: ssm_check.rc != 0
      ignore_errors: yes

    - name: Ensure SSM Agent enabled and started
      service:
        name: amazon-ssm-agent
        state: started
        enabled: yes
      ignore_errors: yes

    # --- Docker ----------------------------------------------------------------
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    # --- Write ENV file --------------------------------------------------------
    - name: Ensure config directory exists
      file:
        path: /etc/movie-analyst
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Write API environment file
      copy:
        dest: /etc/movie-analyst/.env
        mode: "0644"
        content: |
          DB_HOST={{ DB_HOST }}
          DB_USER={{ DB_USER }}
          DB_PASS={{ DB_PASS }}
          DB_NAME={{ DB_NAME }}

    # --- Update /etc/environment ----------------------------------------------
    - name: Persist DB_HOST in /etc/environment
      lineinfile:
        path: /etc/environment
        regexp: "^DB_HOST="
        line: "DB_HOST={{ DB_HOST }}"
        state: present

    # --- Pull & Run Backend Container (CORREGIDO) -----------------------------------------
    - name: Stop existing backend container
      command: docker stop backend
      ignore_errors: yes

    - name: Remove existing backend container
      command: docker rm backend
      ignore_errors: yes

    - name: Pull latest backend image
      command: docker pull {{ APP_IMAGE }}

    - name: Run backend container (with dynamic env vars and METRICS_ENABLED flag)
      command: >
        docker run -d --name backend --restart=always \
        -p 3000:3000 \
        --env-file /etc/movie-analyst/.env \
        -e NODE_ENV={{ RUNTIME_ENV }} \
        -e JAEGER_IP={{ JAEGER_IP }} \
        -e METRICS_ENABLED=true \
        {{ APP_IMAGE }}

    # --- Diagnostics -----------------------------------------------------------
    - name: Show containers
      command: docker ps -a
      ignore_errors: yes

    - name: Show backend logs
      command: docker logs --tail 50 backend
      ignore_errors: yes
