- name: Deploy Frontend App (simple mode)
  hosts: frontend
  become: yes

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    app_image: "{{ app_image }}"
    back_host: "{{ back_host }}"

  tasks:
    - name: Wait for dpkg lock (Ubuntu unattended upgrades)
      shell: |
        while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for dpkg lock..."
          sleep 5
        done
      changed_when: false

    - name: Update APT
      apt:
        update_cache: yes

    - name: Ensure SSM Agent running (if installed)
      service:
        name: amazon-ssm-agent
        state: started
        enabled: yes
      ignore_errors: yes

    - name: Install Docker and tools
      apt:
        name:
          - docker.io
          - curl
          - jq
          - ca-certificates
        state: present

    - name: Ensure Ubuntu user is in Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Ensure Docker is running
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Stop existing frontend container
      shell: docker stop frontend || true

    - name: Remove old container
      shell: docker rm frontend || true

    - name: Run frontend container
      shell: |
        docker run -d --name frontend --restart=always -p 3030:3030 \
          -e NODE_ENV=production \
          -e PORT=3030 \
          -e BACK_HOST="{{ back_host }}" \
          "{{ app_image }}"

    - name: Healthcheck
      uri:
        url: "http://localhost:3030"
        status_code: 200
      register: health
      retries: 10
      delay: 4
      until: health.status == 200
